### ISSUE TITLE
New paper on PM2.5 estimation using deep learning

### ISSUE THREAD

**Issue by MAKassien** [NIEHS/beethoven#237]
Just stumbled upon a paper published this month that may be relevant to the project. It’s from Susan Anenberg’s team, she’s a well established high profile researcher in the air pollution and epidemiology field. 

The paper estimates PM2.5 and black carbon between 2000 and 2020 using a deep forest model to combine EPA observations, satellite, ERA5 meteorology, and others. 

@Spatiotemporal-Exposures-and-Toxicology @mitchellmanware it could be useful to see what exact covariates they used for ideas on anything we haven’t considered or also how to deal with discrepancies in spatial/temporal coverage between different covariates (it looks like they talk about this specifically for satellite observations so it could be of interest to @sigmafelix who’s been working on those too)

https://doi.org/10.1016/S2542-5196(23)00235-8

(I’m away from my computer so posting this through GitHub on my phone, if you’d rather discuss somewhere else we can move this elsewhere later)

**Comment by sigmafelix** [comment]
Thanks for letting us know the very interesting paper @MAKassien ! Their deep forest approach looks interesting. I am trying to adopt a convolutional neural network approach ([paper1](https://doi.org/10.1016/j.cageo.2021.104869)) and attention layer approach ([paper2](https://doi.org/10.1007/s00521-021-05958-z)) as a base learner of our pipeline. The former comes with the fully operational code with `torch`, so I am focusing on that at the moment. It will be also great to discuss dealing with discrepancies between satellite observation datasets soon.
