### ISSUE TITLE
Check all the testthat() for calc_ functions to be consistent with testdata generated by #233

### ISSUE THREAD

**Issue by eva0marques** [NIEHS/beethoven#269]

**Comment by mitchellmanware** [comment]
@eva0marques 
Unit and integration tests for `import_geos` and `covar_geos` are (in production) on the mm-process-functions branch. `import_geos` should be able to run with test GEOS-CF data, and pass cleanded data to `covar_geos`.

Message or comment when data is created, thanks!

**Comment by eva0marques** [comment]
@mitchellmanware 
Nice, thank you. I was thinking that for the moment I should store the testdata locally on the /ddn/gs1/group/set/Projects/NRT-AP-Model/ folder so that you can use the GEOS-CF testdata I extracted for your testing.

**Comment by eva0marques** [comment]
@Spatiotemporal-Exposures-and-Toxicology I want to copy my /ddn/gs1/home/marquesel/NRTAPmodel/NRTAPmodel/testdata/raw folder in the /ddn/gs1/group/set/Projects/NRT-AP-Model/ repository but it sounds that I am not allowed to do that. Do you think you can give me the rights to do it (or do it)

**Comment by mitchellmanware** [comment]
I have copied covariate data into that folder from local. Should be in bash
```
cp /ddn/gs1/home/marquesel/NRTAPmodel/NRTAPmodel/tests/testdata/raw /ddn/gs1/group/set/Projects/NRT-AP-Model/tests/testdata/raw
```

"tests/" folder is missing from your home directory if that is the exact path you used

**Comment by eva0marques** [comment]
I used this exact command line but I had a Permission denied error (and I do not see what you mean, I do have the tests/ folder k
<img width="367" alt="Screenshot 2024-01-23 at 12 53 17 PM" src="https://github.com/Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel/assets/25242529/10cc3182-efda-44bc-8043-aa730b4fdc49">

**Comment by eva0marques** [comment]
Oh ok you're right in my previous message I forgot the tests/ folder but I didn't forget it in my command line :) Thank you for copying the data anyway!

**Comment by kyle-messier** [comment]
@eva0marques @mitchellmanware  Looks like it can be closed. Re-open if needed.
