### ISSUE TITLE
 Future idea: include other terrain covariates 

### ISSUE THREAD

**Issue by eva0marques** [NIEHS/beethoven#270]
From the GMTED data, other covariates can be derived with the function terra::terrain(). For example, the slope, aspect, roughness, flow direction...
Maybe some of them could be relevant for the prediction of PM2.5, with the wind flow in the valleys for example.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
- [ ] future additions: urban buildings (street canyon)

**Comment by sigmafelix** [comment]
[Building Footprint dataset](https://github.com/Microsoft/USBuildingFootprints) would be helpful to derive street canyons.

**Comment by kyle-messier** [comment]
@eva0marques @sigmafelix Good future ideas that will be retained here. I am closing issues not directly related to the current `beethoven` implementation.
