### ISSUE TITLE
Prediction at finer resolution in selected locals

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/beethoven#281]
I read an article on local(ized) difference between air pollution prediction models at moderate and high resolution ([Chambliss et al. 2023](https://www.nature.com/articles/s41370-023-00624-z)), whose co-authors worked with many times with @Spatiotemporal-Exposures-and-Toxicology. Although the data they used is based on the campaign in 2015-2017, I think we could collect local data such as [PurpleAir](https://community.purpleair.com/t/purpleair-data-download-tool/3787) to produce predictions at finer resolution (e.g., 100 meters) in the future. Of course this issue should be included on long-term goals and it needs extensive considerations on calibration, data availability, and time/financial costs. Is the mobile sensor measurement campaign going on recently @Spatiotemporal-Exposures-and-Toxicology ?

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@sigmafelix Yes, Sarah Chambliss was a PhD student with my postdoctoral advisor, Josh Apte, while I was there. Hyper-local air pollution prediction has predominately been done with monitoring such as a mobile monitoring or dense networks. I think adding purple air would be a great extension - why I think having open source and access code base is so critical. It will make this extensions more feasible. But as you say, definitely another analysis and paper for the future. Perhaps something you could write a K99 around 🚀 😜

**Comment by kyle-messier** [comment]
@sigmafelix Let's discuss this whenever we get to future projects or grant applications. As it pertains to `beethoven`, I am closing.

**Comment by sigmafelix** [comment]
For reference:

A preprint on a super-learned model for PM2.5 components:
https://www.researchsquare.com/article/rs-1745433/v2
I think this manuscript is under review for quite a long time, and could not find the published version; either way, I think this is a good reference for the manuscript. Many familiar names on the papers we've navigated are on this paper.
