### ISSUE TITLE
Remove stdt calls in cross_validation functions

### ISSUE THREAD

**Issue by eva0marques** [NIEHS/beethoven#293]
New functions have been created in Amadeus package to facilitate the use of sf and sftime data format instead of ad hoc stdt. We need to modify cross-validation functions in beethoven to remove the calls to stdt format. It implies to load Amadeus in Beethoven or to copy manipulate_space_time_data.R.

**Comment by kyle-messier** [comment]
@mitchellmanware @sigmafelix  I believe this is done.
