### ISSUE TITLE
Buffer radius distances

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/beethoven#302]
I think we discussed this briefly time to time, but did find no clear direction. In #186, we set buffer distances as below. However, the output rds files in the team directory have various distance combinations. Did we decide to use dataset-specific buffer distances?

----
              Buffer radius distances:

- Pixel value
- 1km
- 10km
- 50km

(If resolution is larger than any of the buffers, then only compute pixel value and buffers larger than variable resolution)

_Originally posted by @MAKassien in https://github.com/NIEHS/beethoven/issues/186#issuecomment-1819861696_

**Comment by kyle-messier** [comment]
@sigmafelix Where possible, we should be consistent with buffer or SEDC range sizes. However, for some variables such as coarse resolution gridded data, a 1km buffer may not make sense.
