### ISSUE TITLE
pkgdown 

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/beethoven#310]
We need to get the _pkgdown back and working for`beethoven`

**Comment by sigmafelix** [comment]
@kyle-messier After cleaning up the codebase, we have a very few functions in this package. I think a wrapper function for running/rerunning the pipeline will be helpful for potential users (and also for us). I will put the _pkgdown.yml file back to `main`.

**Comment by sigmafelix** [comment]
In #338, pkgdown webpage will reflect the recent changes in pipeline functions. All functions are classified by `@keywords` tag in Roxygen2 documentation, which is used in _pkgdown.yml for indexing.
