### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/beethoven#311]
The README for `beethoven` is an out-of-date description of our project. We need to make a plan to update the README. What should it include?

**Comment by sigmafelix** [comment]
I think README will reflect the working pipeline. A few ideas coming up now include--the pipeline design, package dependencies, how to run the pipeline, some suggestions for rerun cycle, and the contribution to the reproducible air pollution modeling.

**Comment by kyle-messier** [comment]
@sigmafelix closing due to the introduction of #318
