### ISSUE TITLE
SLURM submission inside a submission

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/beethoven#330]
The pipeline halts after 15-20 minutes when I am signed out from an interactive session after the connection to HPC is cut off. I will figure out if nested submission (i.e., submit a main process where `tar_make()` is run, then it submit SLURM jobs for each target) is possible, then contact the right person to extend the automatic sign-out time.

**Comment by kyle-messier** [comment]
@sigmafelix If using `crew` and `crew.cluster` the idea is that they can submit separate, parallel jobs for each target. I do think we need to figure out how do that given an interactive session on triton or fermi. Are you referring to a process where multiple bash scripts are submitted?

**Comment by sigmafelix** [comment]
@kyle-messier Submission is done automatically with `tar_make_future()` as well, but the problem is that it will work properly only if the main process is active. When I log off from the session or lost connection from onsite or VPN, the main process halts after a few minutes even though the main process is running in the background in one of our interactive nodes (triton or fermi). My idea is to run a main process via SLURM where `tar_make_future()` is run there. It appears that SLURM commands run in an interactive session via `srun` to `geo`, so I believe it will work. I will follow up with this issue.

**Comment by sigmafelix** [comment]
I confirmed that submitting slurm jobs in a slurm job is working in `targets` context.
