### ISSUE TITLE
covariate missing imputation

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/beethoven#331]

**Comment by kyle-messier** [comment]
Covariates with missing values:

- [ ] MODIS

**Comment by kyle-messier** [comment]
General approach:
If < 5%, moving window average or NN interpolation
If in the 5-30% range, a simple model such as a LR or IDW

**Comment by kyle-messier** [comment]
Approach we decided on:
1) calc_modis functions can return an NA (Missing) - 
2) Calculate all of the covariates - get covariate matrix in pipeline
3) RandomForest model uses covariate matrix to impute missing data (including all other covariates) at the PM2.5 locations 
4) Flag for points with excessive missing

**Comment by sigmafelix** [comment]
@kyle-messier 

The imputation procedure is implemented as follows:
1. Excluding zero variance features
2. Replace `NaN`s into `NA`s
3. For NDVI feature, filling in the missing previous 15-day values with the nearest available value ahead as 16-day NDVI is based on the 16 days period
4. Replacing `NA`s with zeros in non-MODIS/VIIRS (except for NDVI) features
5. Running `missRanger`

----
Further discussion items:
- Do we include the missing rate/imputation flag in a separate target?
- Do we tune hyperparameters for the imputation model or use predefined values?

**Comment by kyle-messier** [comment]
@sigmafelix You reported the `targets` pipeline has implemented this, so I am closing.
