### ISSUE TITLE
NARR SHUM is read as all `NA`s in cells on HPC

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/beethoven#333]
I found that NARR SHUM (specific humidity) layers are read as all `NA`s in HPC. I checked four different situations that would provide hints for the reason of this problem:

1. Opened in an interactive session on `triton`: all `NA`s.
2. Re-downloaded file directly from the source: all `NA`s.
3. Loaded in laptop: read properly
4. Opened files in Apptainer image in HPC: read properly

The difference between 1-4 is GDAL version, where the versions are 3.0.4, 3.0.4, 3.5.3, and 3.4.3, respectively. One strange thing in this issue is that omega, the other pressure level variable, had no issue in reading values. Since we rely on HPC's own system libraries and R installation, we don't have much to do with updating GDAL there. I think `shum` variables will be calculated locally or on apptainer image (either way, this step is apart from the pipeline) then appended to the other covariates.

@kyle-messier @mitchellmanware

**Comment by mitchellmanware** [comment]
That is really strange, but I recall something similar occurring a few months ago. If you it could be an issue with the data files themselves (since omega variables are fine), could it be worth contacting the NOAA point of contact for this dataset?
@sigmafelix

**Comment by kyle-messier** [comment]
@sigmafelix @mitchellmanware  Situation 2 is perhaps the most concerning since you are saying that a direct download from the NASA source results in `NA`s. @sigmafelix is that whether it is downloaded locally or on the HPC?

**Comment by sigmafelix** [comment]
@kyle-messier I realized that my wording was unclear. I tested downloading both locally and on the HPC, and found that the data was not a problem (i.e., comparing 1 and 3 with local and HPC copies).

**Comment by kyle-messier** [comment]
@sigmafelix @mitchellmanware I'll add this to our meeting agenda to discuss.

**Comment by sigmafelix** [comment]
I think the issue is documented here: https://github.com/OSGeo/gdal/issues/4443 and bug fix report is available at https://github.com/OSGeo/gdal/blob/e0fe70c8bd98350f33f729b2dc3cdfc2ae45ebae/gdal/NEWS#L72. I see the same issue with QGIS on my laptop, which uses GDAL 3.3.2. Apparently this issue can be resolved if we use GDAL 3.3.3+.

**Comment by kyle-messier** [comment]
That's great @sigmafelix. You can proceed with contacting Frank or whatever is needed to update GDAL on GEO. 🚀

**Comment by sigmafelix** [comment]
Frank is experimenting on configuring different GDAL versions in HPC. I will keep y'all updated.

**Comment by sigmafelix** [comment]
@kyle-messier A quick update from Frank: he configured GDAL 3.8.5 for me by copying a folder with library files. I inquired how this solution can be applied to everyone. I will continue work on the pipeline.

**Comment by sigmafelix** [comment]
As a side note, the workaround is only available in triton. I think it depends on the system configuration in each node.
