### ISSUE TITLE
Refactor `init/targets/targets_download`

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/beethoven#362]
# Refactor 0.4.1 `init/targets/targets_download` 

See for sketch: https://github.com/NIEHS/beethoven/issues/361#issuecomment-2383452703
 
- [x] initialization 
- [x] tar_target per variable. This could be a dataset (e.g. NLCD) or a dataset+variable (e.g. MODIS MOD09GA)
- [x] `pattern =` configuration

**Comment by mitchellmanware** [comment]
@kyle-messier 
For the argument setup, do we want to continue using the `loadargs(file_prep_calc_args, ...)` method for arguments, where `file_prep_calc_args` is the path to the `calc_spec.qs` file? Or should we transition all to a `targets`-based approach, where all argument functions are stored as targets not file paths?

**Comment by kyle-messier** [comment]
I think we have one line of code in `_targets.R` that specifies the time range desired, then that feeds into the first target. Then initialization occurs through targets, so I guess more or less the latter.
