### ISSUE TITLE
merge recent `crew`, `apptainer` tests to `main`

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/beethoven#364]
- [x] Develop a plan to merge recent tests from @kyle-messier and @mitchellmanware to provide a start for refactoring

**Comment by mitchellmanware** [comment]
@kyle-messier
Maybe we should make a `dev/` folder on the repo to store `crew`, `apptainer` and refactoring development work. I think if it is in a different folder and we explicitly set the `tar_store()` we can develop within the context of a target pipeline.

**Comment by kyle-messier** [comment]
1. Creating a separate `dev/` branch 
2. @kyle-messier branch on crew tests will be left alone
